-- Your SQL goes here

CREATE TABLE IF NOT EXISTS nodes (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  notes TEXT NOT NULL DEFAULT "", 

  startdue INTEGER DEFAULT NULL, 
  deadline INTEGER DEFAULT NULL, 

  done BOOL NOT NULL DEFAULT FALSE, 
  started BOOL NOT NULL DEFAULT FALSE,

  is_open BOOL NOT NULL DEFAULT FALSE,

  done_time TIMESTAMP DEFAULT NULL,
  started_time TIMESTAMP DEFAULT NULL,

  parent_id INTEGER DEFAULT NULL,
  FOREIGN KEY (parent_id) REFERENCES nodes(id)
  ON DELETE CASCADE
);
