-- Your SQL goes here

CREATE TABLE IF NOT EXISTS nodes (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  startdue INTEGER DEFAULT NULL, 
  deadline INTEGER DEFAULT NULL, 
  notes TEXT DEFAULT "", 
  done BOOL NOT NULL DEFAULT FALSE, 
  started BOOL NOT NULL DEFAULT FALSE,
  parent_id INTEGER DEFAULT NULL,
  is_open BOOL NOT NULL DEFAULT FALSE,
  FOREIGN KEY (parent_id) REFERENCES node(id)
  ON DELETE CASCADE
);
